### PR TITLE
Math Magicians: tests

### PR DESCRIPTION
**Pull request by quavo19**
in this milestone, @Anand8317  and I;

- Set up a React Testing Library called jest.
- Wrote unit tests for the files operate.js and calculate.js using Jest.
- Created unit tests for all React components:

### CODE REVIEW

**Review by Danieldotcomcoder — CHANGES_REQUESTED** [review]
Hello @quavo19  & @Anand8317 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Professional Readme File ✔✔
- Linters are setup correctly ✔✔
- All Tests are passing ✔✔

## Required Changes ♻️

Kindly you need to use Jest snapshots to tests all components (home.js, nav.js etc ...) , currently you are only using Jest snapshot for App.js. 👍 

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by quavo19** [comment]
sir @Danieldotcomcoder the app contains all the components I need to test so id didn't see why I should import them since it works the same

**Comment by quavo19** [comment]
@Danieldotcomcoder and also the test covers all components

**Comment by Danieldotcomcoder** [comment]
> sir @Danieldotcomcoder the app contains all the components I need to test so id didn't see why I should import them since it works the same

Hello, It is required to use Jest snapshots to test all components , not only the app component even if it contains all the other components.

**Comment by quavo19** [comment]
@Danieldotcomcoder  I'm using a click to toggle every component instead of importing too many paths, so it works the same.
the goal is to test all components and that's exactly what I did sir 😢 
Screenshot (66)

**Comment by Danieldotcomcoder** [comment]
> @Danieldotcomcoder I'm using a click to toggle every component instead of importing too many paths, so it works the same. the goal is to test all components and that's exactly what I did sir 😢 Screenshot (66)

I understand, but when I run your tests I can see only one snapshot created, but its supposed to be one snapshot for each component.

**Comment by quavo19** [comment]
@Danieldotcomcoder sir please I don't think its part of the requirements
Screenshot (68)

they could have said for each.

**Review by jasonfelice — APPROVED** [review]
Hi @quavo19, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<p align="center"></p>

## Highlights
No Linter errors✔️
All tests are passing✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
